variables:
  MESSAGE: "hello world from gitlab ci/cd!"
  FILE_NAME: test_file.txt
  DIR_NAME: demo

image: alpine:latest

stages:
 - prep
 - create
 - test

prep the environment:
  stage: prep
  script:
    - mkdir $DIR_NAME
  artifacts:
    paths:
      - $DIR_NAME/

create the file:
  stage: create
  script:
    - echo $MESSAGE > $DIR_NAME/$FILE_NAME
  artifacts:
    paths:
      - $DIR_NAME/

test the file:
  stage: test
  script:
    - test -d $DIR_NAME
    - grep -q "$MESSAGE" $DIR_NAME/$FILE_NAME
